### ISSUE TITLE
Abandoned??

### ISSUE THREAD

**Issue by user-987654321** [hashicorp/terraform-provider-azurestack#139]
If this has been abandoned can it be made clear

Thanks

**Comment by tombuildsstuff** [comment]
hi @user-987654321 

Thanks for opening this issue.

The Azure Stack provider remains a fully supported Provider and is not abandoned, however the nature of the Azure Stack product means that there's less functionality being added to Azure Stack relative to Azure Public.

Since this is a question rather than a bug in the Provider and this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but should you have further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
