### ISSUE TITLE
azurerm_virtual_machine_extension - typeHandlerVersion with InvalidParameter

### ISSUE THREAD

**Issue by bayerb** [hashicorp/terraform-provider-azurestack#140]
Hi,

running apply on code

resource "azurerm_virtual_machine_extension" "vm-bootstrap" {
 count = "1"
 name                 = "bootstrap"
 virtual_machine_id = ...
 publisher            = "Microsoft.Azure.Extensions"
 type                 = "CustomScript"
 type_handler_version = "2.1.6"
 settings = <<SETTINGS
   {
      "script": "${filebase64("bootstrap.sh")}"
   }
SETTINGS
} 

returns the following error:

Code="InvalidParameter" Message="The value of parameter typeHandlerVersion is invalid." Target="typeHandlerVersion"

though it looks like version 2.1.6 exists:

az vm extension image list-versions -n CustomScript --publisher Microsoft.Azure.Extensions --lo
cation westeurope --query "[].name" -o tsv | sort -u
2.0.0
2.0.1
2.0.2
2.0.3
2.0.4
2.0.5
2.0.6
2.0.7
2.1.1
2.1.2
2.1.3
2.1.6

Can you please check?

**Comment by tombuildsstuff** [comment]
hi @bayerb 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Stack Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
